"""Add service parts and job details

Revision ID: f7b4f08bd82e
Revises: 25339ad384f1
Create Date: 2025-07-12 15:43:04.576731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b4f08bd82e'
down_revision = '25339ad384f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_part_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_job_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_service_part_usage_product_id_product')),
    sa.ForeignKeyConstraint(['service_job_id'], ['service_job.id'], name=op.f('fk_service_part_usage_service_job_id_service_job')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_part_usage'))
    )
    with op.batch_alter_table('service_part_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_part_usage_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_part_usage_service_job_id'), ['service_job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_part_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_part_usage_service_job_id'))
        batch_op.drop_index(batch_op.f('ix_service_part_usage_product_id'))

    op.drop_table('service_part_usage')
    # ### end Alembic commands ###
